rules:
  flights:
    max_price_usd: 300
  hilton:
    max_points_per_night: 20000

months:
  - "2026-02"
  - "2026-03"
  - "2026-05"
  - "2026-06"
  - "2026-07"
  - "2026-08"
  - "2026-09"
  - "2026-10"
  - "2026-11"
  - "2026-12"

targets:
  flights:
    - name: "EL AL Flight Deals (EN)"
      url: "https://www.elal.com/flight-deals/en-il/"
    - name: "EL AL Flight Deals (HE)"
      url: "https://www.elal.com/flight-deals/he-il/"

  hilton_places:
    berlin:
      query: "Berlin, Germany"
      placeId: "dx-location::locality::de::berlin"

    london:
      query: "London, United Kingdom"
      placeId: "dx-location::locality::gb::london"

    barcelona:
      query: "Barcelona, Spain"
      placeId: "dx-location::locality::es::barcelona"

    newyork:
      query: "New York, NY, United States"
      placeId: "dx-location::locality::us::new-york"

    newark:
      query: "Newark, NJ, United States"
      placeId: "dx-location::locality::us::newark"

    paris:
      query: "Paris, France"
      placeId: "dx-location::locality::fr::paris"

    vienna:
      query: "Vienna, Austria"
      placeId: "dx-location::locality::at::vienna"

    copenhagen:
      query: "Copenhagen, Denmark"
      placeId: "dx-location::locality::dk::copenhagen"

    stockholm:
      query: "Stockholm, Sweden"
      placeId: "dx-location::locality::se::stockholm"
